# Generated by Django 2.2 on 2019-05-28 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('chain_num', models.CharField(default='0', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_num', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nonce', models.CharField(default='0', max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('timestamp', models.CharField(default='0', max_length=100)),
                ('hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=100)),
                ('previous_hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=100)),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hash.Blockchain')),
            ],
        ),
    ]
