# Generated by Django 2.2 on 2019-04-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_num', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
            ],
        ),
    ]
