# Generated by Django 2.2 on 2019-04-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash', '0002_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='nonce',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
